import type { LocalizationGenConfig } from "../types/config.js";
import type { RuntimeManifest } from "../types/manifest.js";
import { buildRuntimeModel } from "./build-runtime-model.js";

/**
 * Convert a PascalCase `class_name` (e.g. `AppLocalizations`, `LibLocalizations`)
 * into the set of identifiers emitted by the runtime entry / types files.
 *
 * The convention is:
 *   - manifest type:        `${Base}Manifest`      (e.g. `AppLocalizationManifest`)
 *   - accessor node type:   `${Base}Node`          (e.g. `AppLocalizationNode`)
 *   - accessor tree alias:  `${Base}`              (e.g. `AppLocalization`)
 *   - manifest const:       `${base}Manifest`      (e.g. `appManifest`)
 *   - accessor const:       `${base}Localization`  (e.g. `appLocalization`)
 *
 * `Base` strips a trailing "s" from `class_name` and preserves the rest.
 * `base` is the camelCase form of `Base` (first letter lowercased).
 */
function deriveRuntimeNames(className: string): {
  ManifestType: string;
  NodeType: string;
  RootType: string;
  manifestConst: string;
  accessorConst: string;
} {
  const pascal = className.endsWith("s") && className.length > 1 ? className.slice(0, -1) : className;
  const camel = pascal.charAt(0).toLowerCase() + pascal.slice(1);
  return {
    ManifestType: `${pascal}Manifest`,
    NodeType: `${pascal}Node`,
    RootType: pascal,
    manifestConst: `${camel}Manifest`,
    accessorConst: camel
  };
}

export function buildReactRuntimeFiles(
  manifest: RuntimeManifest,
  config: Pick<LocalizationGenConfig, "class_name" | "generated">
): { entry: string; types: string } {
  const model = buildRuntimeModel(manifest);
  const names = deriveRuntimeNames(config.class_name);
  // The runtime entry imports types from the sibling types file. Strip the
  // .ts extension so it works under both .ts and .d.ts emitted output.
  const typesImportPath = config.generated.runtime_types_file.replace(/\.ts$/, "");
  const entry = `/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by localization-gen-core.
// This file contains runtime localization manifest data used by adapters.

import type { ${names.ManifestType}, ${names.NodeType} } from "./${typesImportPath}";

const ${names.manifestConst}: ${names.ManifestType} = ${JSON.stringify(manifest, null, 2)} as const;

/**
 * Type-safe accessor tree — property names preserve source key segments.
 * Leaf values are full message keys for use with store.t().
 */
export const ${names.accessorConst} = ${JSON.stringify(model.stringsTree, null, 2)} as const satisfies ${names.NodeType};

/**
 * Exact type of the generated ${names.accessorConst} accessor tree.
 * Preserves all literal string types at every leaf.
 */
export type ${names.RootType} = typeof ${names.accessorConst};

export default ${names.manifestConst};
`;

  const types = `/* eslint-disable */
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by localization-gen-core.
// This file contains runtime localization manifest typings used by adapters.

/**
 * One flattened localization key metadata entry.
 * - key: fully-qualified key (module.path.to.leaf)
 * - placeholders: interpolation variable names used by the message
 */
export interface RuntimeManifestEntry {
  key: string;
  placeholders: string[];
}

/**
 * Runtime manifest consumed by adapter/provider at application runtime.
 */
export interface ${names.ManifestType} {
  /** Default locale used when app starts. */
  base_locale: string;
  /** Locale used when key is missing in active locale. */
  fallback_locale: string;
  /** Locales included in the generated payload. */
  locales: string[];
  /** Flattened key metadata used to build helper accessors. */
  entries: RuntimeManifestEntry[];
  /** Per-locale flat key/value message map. */
  messages: Record<string, Record<string, string>>;
}

/**
 * Base shape for the generated accessor tree.
 * Every leaf is a fully-qualified message key string;
 * every branch is a nested ${names.NodeType}.
 */
export type ${names.NodeType} = {
  readonly [key: string]: string | ${names.NodeType};
};
`;

  return { entry, types };
}