import type { RuntimeManifest } from "../types/manifest.js";
import { buildRuntimeModel } from "./build-runtime-model.js";

export function buildReactRuntimeFiles(manifest: RuntimeManifest): { entry: string; types: string } {
  const model = buildRuntimeModel(manifest);
  const entry = `/* eslint-disable */\n// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.\n// Generated by localization-gen-core.\n// This file contains runtime localization manifest data used by adapters.\n\nimport type { AppLocalizationManifest } from "./app-localization.types";\n\nconst manifest: AppLocalizationManifest = ${JSON.stringify(manifest, null, 2)} as const;\n\n/**\n * Type-safe accessor tree — property names preserve source key segments.\n * Leaf values are full message keys for use with store.t().\n */\nexport const appLocalization = ${JSON.stringify(model.stringsTree, null, 2)} as const;\n\nexport default manifest;\n`;

  const types = `/* eslint-disable */\n// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.\n// Generated by localization-gen-core.\n// This file contains runtime localization manifest typings used by adapters.\n\n/**\n * One flattened localization key metadata entry.\n * - key: fully-qualified key (module.path.to.leaf)\n * - placeholders: interpolation variable names used by the message\n */\nexport interface RuntimeManifestEntry {\n  key: string;\n  placeholders: string[];\n}\n\n/**\n * Runtime manifest consumed by adapter/provider at application runtime.\n */\nexport interface AppLocalizationManifest {\n  /** Default locale used when app starts. */\n  base_locale: string;\n  /** Locale used when key is missing in active locale. */\n  fallback_locale: string;\n  /** Locales included in the generated payload. */\n  locales: string[];\n  /** Flattened key metadata used to build helper accessors. */\n  entries: RuntimeManifestEntry[];\n  /** Per-locale flat key/value message map. */\n  messages: Record<string, Record<string, string>>;\n}\n`;

  return { entry, types };
}
